# Taps
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/services'
tap 'homebrew/cask-fonts'
tap 'hashicorp/tap'
tap 'bufbuild/buf'
tap 'ankitpokhrel/jira-cli' # JIRA

# Brews
brew 'ruby'
brew 'gnu-sed'
berw 'coreutils'
brew 'rbenv'
brew 'bat'
brew 'bat'
brew 'buf'
brew 'fd'
brew 'ffmpeg'
brew 'fzf'
brew 'fd'
brew 'gh'
brew 'git'
brew 'go'
brew 'rust'
brew 'grpc'
brew 'jq'
brew 'k3d'
brew 'graphviz'
brew 'ipcalc'
brew 'iperf'
brew 'jq'
brew 'k3d'
brew 'k6'
brew 'ko'
brew 'kubectl'
brew 'minikube'
brew 'mkcert'
brew 'neovim'
brew 'nmap'
brew 'node'
brew 'protoc-gen-go-grpc'
brew 'ripgrep'
brew 'terraform'
brew 'terraform-ls'
brew 'tig'
brew 'tree'
brew 'watch'
brew 'zoxide'
brew 'mas'
brew 'jira-cli'
brew 'argocd'
brew 'kubectl-argo-rollouts'
brew 'choosy'

# Casks
cask 'rectangle'
cask 'alacritty'
cask 'firefox'
cask 'iterm2'
cask 'docker'
cask 'firefox'
cask 'google-cloud-sdk'
cask 'iina'
cask 'osquery'
cask 'signal'
cask 'whatsapp'
cask 'slack'
# cask 'tableplus@5.3.5'
cask 'whatsapp'
cask 'zoom'
cask 'openlens'
cask 'kap'
cask 'alfred'
cask 'raycast'
cask 'iina'
cask 'google-drive'
cask 'fig'
cask 'goland'
cask 'visual-studio-code'
cask 'spotify'
cask 'arc'
cask 'hiddenbar'
cask 'notion'

# Fonts
cask 'font-fira-code'
cask 'font-fira-code-nerd-font'

# App Store
mas "Copy'em", id: 876540291
mas "Tailscale", id: 1475387142
