# ~/.config/starship.toml

# move the rest of the prompt to the right
right_format = """$kubernetes"""

[kubernetes]
format = '☸ [$context \($namespace\)]($style)'
disabled = false
contexts = [
  { context_pattern = "prd.*", style = "red", symbol = "💔 " },
  { context_pattern = "stg", style = "yellow", symbol = "💔 " },
  { context_pattern = "dev", style = "green", symbol = "💔 " },
]

[gcloud]
disabled = true

[buf]
disabled = true

[line_break]
disabled = true

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

