alias reload!=". ~/.zshrc"
alias ..="cd .."
alias ...="cd ../.."
alias ls="eza --color=always --git --no-user --no-permissions --icons=always --group-directories-first"
alias ll="ls --long"
alias vd="viddy"
alias c="clear"
