# Personal aliases loaded after Omarchy defaults. Avoid ga, gd, and gcm because
# Omarchy reserves them for worktree and commit workflows.
alias reload-shell='source ~/.bashrc'
alias la='ls -a'
alias v='nvim'
alias vi='nvim'
alias vim='nvim'
command -v viddy >/dev/null 2>&1 && alias vd='viddy'

alias gaa='git add --all'
alias gapa='git add --patch'
alias gau='git add --update'
alias gb='git branch'
alias gba='git branch --all'
alias gbd='git branch --delete'
alias gc='git commit --verbose'
alias gcmsg='git commit -m'
alias gco='git checkout'
alias gcp='git cherry-pick'
alias gf='git fetch'
alias gfa='git fetch --all --prune --jobs=10'
alias gl="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias glo='git log --oneline --decorate'
alias glog='git log --oneline --decorate --graph'
alias gloga='git log --oneline --decorate --graph --all'
alias gp='git push'
alias gpf='git push --force-with-lease'
alias gpr='git pull --rebase'
alias grb='git rebase'
alias grba='git rebase --abort'
alias grbc='git rebase --continue'
alias grbi='git rebase --interactive'
alias grs='git restore'
alias grst='git restore --staged'
alias gst='git status'
alias gss='git status --short'
alias gsw='git switch'
alias gswc='git switch --create'

alias kc='kubectl'
alias k='kubectl config use-context'
alias kca='kubectl get all --all-namespaces'
alias kgp='kubectl get pods'

alias za='zellij attach'
alias z='zellij'
alias vz='zellij --layout "$DOTFILES_ROOT/zellij/layouts/nvim-claude.kdl"'
alias voc='zellij --layout "$DOTFILES_ROOT/zellij/layouts/nvim-oc.kdl"'

alias gssh='gcloud beta compute ssh --ssh-key-file ~/.ssh/id_ed25519 --tunnel-through-iap'
alias gcpctx='gcloud config get-value project'

alias agents-encrypt='openssl enc -aes-256-cbc -pbkdf2 -in "$DOTFILES_ROOT/opencode/AGENTS.md" -out "$DOTFILES_ROOT/opencode/AGENTS.md.enc"'
alias agents-decrypt='openssl enc -aes-256-cbc -pbkdf2 -d -in "$DOTFILES_ROOT/opencode/AGENTS.md.enc" -out "$DOTFILES_ROOT/opencode/AGENTS.md"'
